// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: converter/converter.proto

package converter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConverterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *ConverterReq) Reset() {
	*x = ConverterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_converter_converter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConverterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConverterReq) ProtoMessage() {}

func (x *ConverterReq) ProtoReflect() protoreflect.Message {
	mi := &file_converter_converter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConverterReq.ProtoReflect.Descriptor instead.
func (*ConverterReq) Descriptor() ([]byte, []int) {
	return file_converter_converter_proto_rawDescGZIP(), []int{0}
}

func (x *ConverterReq) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type ConverterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *ConverterResp) Reset() {
	*x = ConverterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_converter_converter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConverterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConverterResp) ProtoMessage() {}

func (x *ConverterResp) ProtoReflect() protoreflect.Message {
	mi := &file_converter_converter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConverterResp.ProtoReflect.Descriptor instead.
func (*ConverterResp) Descriptor() ([]byte, []int) {
	return file_converter_converter_proto_rawDescGZIP(), []int{1}
}

func (x *ConverterResp) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

var File_converter_converter_proto protoreflect.FileDescriptor

var file_converter_converter_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x74, 0x65, 0x72, 0x22, 0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x23, 0x0a, 0x0d, 0x43, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x66,
	0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x32,
	0x57, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x54, 0x6f,
	0x50, 0x44, 0x46, 0x12, 0x17, 0x2e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x72, 0x2e,
	0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x63,
	0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x61, 0x70, 0x70, 0x2f,
	0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_converter_converter_proto_rawDescOnce sync.Once
	file_converter_converter_proto_rawDescData = file_converter_converter_proto_rawDesc
)

func file_converter_converter_proto_rawDescGZIP() []byte {
	file_converter_converter_proto_rawDescOnce.Do(func() {
		file_converter_converter_proto_rawDescData = protoimpl.X.CompressGZIP(file_converter_converter_proto_rawDescData)
	})
	return file_converter_converter_proto_rawDescData
}

var file_converter_converter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_converter_converter_proto_goTypes = []interface{}{
	(*ConverterReq)(nil),  // 0: converter.ConverterReq
	(*ConverterResp)(nil), // 1: converter.ConverterResp
}
var file_converter_converter_proto_depIdxs = []int32{
	0, // 0: converter.ConverterService.ConvertToPDF:input_type -> converter.ConverterReq
	1, // 1: converter.ConverterService.ConvertToPDF:output_type -> converter.ConverterResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_converter_converter_proto_init() }
func file_converter_converter_proto_init() {
	if File_converter_converter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_converter_converter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConverterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_converter_converter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConverterResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_converter_converter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_converter_converter_proto_goTypes,
		DependencyIndexes: file_converter_converter_proto_depIdxs,
		MessageInfos:      file_converter_converter_proto_msgTypes,
	}.Build()
	File_converter_converter_proto = out.File
	file_converter_converter_proto_rawDesc = nil
	file_converter_converter_proto_goTypes = nil
	file_converter_converter_proto_depIdxs = nil
}
